export enum apiRoutes {
  LOGIN = '/auth/login',
  SIGNUP = '/auth/signup',
  SIGNOUT = '/auth/signout',
  REFRESH_TOKENS = '/auth/refresh',
  FETCH_ME = '/auth',
  FETCH_USER = '/me',
  FETCH_QUOTES_NUMBER = '/me',
  FETCH_VOTES_NUMBER = '/me',
  USERS_PREFIX = '/users',
  UPLOAD_AVATAR_IMAGE = '/users/upload',
  UPLOAD_PRODUCT_IMAGE = '/products/upload',
  GET_AVATAR_IMAGE = '/users/get/image',
  FETCH_QUOTE = '/quotes',
}
